package com.fitback.domain.customer.enums;

public enum CustomerActivityType {
    CONSULTATION_CREATED,
    RECONSULTATION_CREATED,
    AI_ANALYSIS_COMPLETED,
    AI_ANALYSIS_FAILED,
    AI_ANALYSIS_MANUALLY_UPDATED,
    NEXT_ACTION_CREATED,
    NEXT_ACTION_REGENERATED,
    CUSTOMER_STATUS_CHANGED,
    FOLLOW_UP_CREATED,
    MESSAGE_TEMPLATE_CREATED,
    MESSAGE_TEMPLATE_COPIED,
    MESSAGE_SENT,
    FOLLOW_UP_COMPLETED
}
